---
title: "Publications"
toc: true
title-block-banner: true
sidebar: true
---


### Preprints

J. David Wong-Campos, Dalia P. Ornelas-Huerta, Mackenzie Dion. [Two-step excitation of fluorescent proteins with real intermediary states](https://arxiv.org/abs/2503.18000). *arXiv*, 2025.

J. David Wong-Campos, Mackenzie Dion. [Multiphoton fluorescence excitation with real intermediary states](https://arxiv.org/abs/2501.18706). *arXiv*, 2025.

Daniel G. Itkis, F. Phil Brooks III, Hunter C. Davis, Raphael Hotter, J. David Wong-Campos, Yitong Qi, Bill Z. Jia, Madeleine Howell, Marley Xiong, Rebecca Frank Hayward, Adam E. Cohen. [Luminos: open-source software for bidirectional microscopy](https://www.biorxiv.org/content/10.1101/2025.01.17.633555v1). *bioRxiv*, 2025.

J. David Wong-Campos*, Pojeong Park*, Hunter C. Davis, Yitong Qi, He Tian, Daniel G. Itkis, Doyeon Kim, Jonathan B. Grimm, Sarah E. Plutkis, Luke D. Lavis, Adam E. Cohen. [Voltage dynamics of dendritic integration and back-propagation in vivo](https://www.biorxiv.org/content/10.1101/2023.05.25.542363v1). *bioRxiv*, 2023.

### 2026

J. David Wong-Campos†, Pojeong Park†, Byung Hun Lee†, Hunter C. Davis, Yitong Qi, He Tian, Daniel G. Itkis, Doyeon Kim, Jonathan B. Grimm, Sarah E. Plutkis, Luke D. Lavis, Adam E. Cohen. [Voltage dynamics of dendritic integration and back-propagation in vivo](). In press, 2026.


### 2025

Doyeon Kim, Pojeong Park, Xiuyuan Li, J. David Wong-Campos, He Tian, Eric M. Moult, Jonathan B. Grimm, Luke D. Lavis, Adam E. Cohen. [EPSILON: a method for pulse-chase labeling to probe synaptic AMPAR exocytosis during memory formation](https://www.nature.com/articles/s41593-024-01922-5). *Nature Neuroscience*, 2025.

Pojeong Park†, J. David Wong-Campos†, Daniel G. Itkis, Byung Hun Lee, Yitong Qi, Hunter C. Davis, Benjamin Antin, Amol Pasarkar, Jonathan B. Grimm, Sarah E. Plutkis, Luke D. Lavis, Adam E. Cohen. [Dendritic excitations govern back-propagation via a spike-rate accelerometer](https://www.nature.com/articles/s41467-025-55819-9). *Nature Communications*, 2025.

### 2024

F. Phil Brooks III, Hunter C. Davis, J. David Wong-Campos, Adam E. Cohen. [Optical constraints on two-photon voltage imaging](https://www.spiedigitallibrary.org/journals/neurophotonics/volume-11/issue-3/035007/Optical-constraints-on-two-photon-voltage-imaging/10.1117/1.NPh.11.3.035007.full). *Neurophotonics*, 2024.

### 2023

Bill Z. Jia, Yitong Qi, J. David Wong-Campos, Sean G. Megason, Adam E. Cohen. [A bioelectrical phase transition patterns the first vertebrate heartbeats](https://www.nature.com/articles/s41586-023-06561-z). *Nature*, 2023.

He Tian, Hunter C. Davis, J. David Wong-Campos, Pojeong Park, Linlin Z. Fan, Benjamin Gmeiner, Shahinoor Begum, Christopher A. Werley, Gabriel B. Borja, Hansini Upadhyay, Himali Shah, Jane Jacques, Yitong Qi, Vicente Parot, Karl Deisseroth, Adam E. Cohen. [Video-based pooled screening yields improved far-red genetically encoded voltage indicators](https://www.nature.com/articles/s41592-022-01743-5). *Nature Methods*, 2023.

### 2022

Andrew T. Landau, Pojeong Park, J. David Wong-Campos, He Tian, Adam E. Cohen, Bernardo L. Sabatini. [Dendritic branch structure compartmentalizes voltage-dependent calcium influx in cortical layer 2/3 pyramidal cells](https://elifesciences.org/articles/76993). *eLife*, 2022.

### 2021

J. David Wong-Campos, J. V. Porto, Adam E. Cohen. [Which way does stimulated emission go?](https://pubs.acs.org/doi/10.1021/acs.jpca.1c07713). *Journal of Physical Chemistry A*, 2021.

### 2020

Yunseong Nam, Jwo-Sy Chen, Neal C. Pisenti, Kenneth Wright, Conor Delaney, Dmitri Maslov, Kenneth R. Brown, Stewart Allen, Jason M. Amini, Joel Apisdorf, Kristin M. Beck, Aleksey Blinov, Vandiver Chaplin, Mika Chmielewski, Coleman Collins, Shantanu Debnath, Andrew M. Ducore, Kai M. Hudek, Matthew Keesan, Sarah M. Kreikemeier, Jonathan Mizrahi, Phil Solomon, Mike Williams, J. David Wong-Campos, Christopher Monroe, Jungsang Kim. [Ground-state energy estimation of the water molecule on a trapped-ion quantum computer](https://www.nature.com/articles/s41534-020-0259-3). *npj Quantum Information*, 2020.

Juan F. Yee-de León, Brenda Soto-García, Diana Aráiz-Hernández, Jesús Rolando Delgado-Balderas, Miguel Esparza, Carlos Aguilar-Avelar, J. David Wong-Campos, Franco Chacón, José Y. López-Hernández, A. Mauricio González-Treviño, José R. Yee-de León, Jorge L. Zamora-Mendoza, Mario M. Alvarez, Grissel Trujillo-de Santiago, Lauro S. Gómez-Guerra, Celia N. Sánchez-Domínguez, Liza P. Velarde-Calvillo, Alejandro Abarca-Blanco. [Characterization of a novel automated microfiltration device for the efficient isolation and analysis of circulating tumor cells from clinical blood samples](https://www.nature.com/articles/s41598-020-64713-4). *Scientific Reports*, 2020.

### 2019

Carlos Aguilar-Avelar, Brenda Soto-García, Diana Aráiz-Hernández, Juan F. Yee-de León, Miguel Esparza, Franco Chacón, Jesús Rolando Delgado-Balderas, Mario M. Alvarez, Grissel Trujillo-de Santiago, Lauro S. Gómez-Guerra, Liza P. Velarde-Calvillo, Alejandro Abarca-Blanco, J. David Wong-Campos. [High-throughput automated microscopy of circulating tumor cells](https://www.nature.com/articles/s41598-019-50027-w). *Scientific Reports*, 2019.

Kenneth Wright, Kristin M. Beck, Shantanu Debnath, Jason M. Amini, Yunseong Nam, Nade Grzesiak, Jwo-Sy Chen, Neal C. Pisenti, Mika Chmielewski, Coleman Collins, Kai M. Hudek, Jonathan Mizrahi, J. David Wong-Campos, Stewart Allen, Joel Apisdorf, Phil Solomon, Mike Williams, Andrew M. Ducore, Aleksey Blinov, Sarah M. Kreikemeier, Vandiver Chaplin, Matthew Keesan, Christopher Monroe, Jungsang Kim. [Benchmarking an 11-qubit quantum computer](https://www.nature.com/articles/s41467-019-13534-2). *Nature Communications*, 2019.

### 2017

J. David Wong-Campos, Steven A. Moses, Kale G. Johnson, Christopher Monroe. [Demonstration of two-atom entanglement with ultrafast optical pulses](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.119.230501). *Physical Review Letters*, 2017.

Kale G. Johnson, J. David Wong-Campos, Brian Neyenhuis, Jonathan Mizrahi, Christopher Monroe. [Ultrafast creation of large Schrödinger cat states of an atom](https://www.nature.com/articles/s41467-017-00682-6). *Nature Communications*, 2017.

### 2016

J. David Wong-Campos, Kale G. Johnson, Brian Neyenhuis, Jonathan Mizrahi, Christopher Monroe. [High-resolution adaptive imaging of a single atom](https://www.nature.com/articles/nphoton.2016.136). *Nature Photonics*, 2016.

Kale G. Johnson, J. David Wong-Campos, Alessandro Restelli, Kyle A. Landsman, Brian Neyenhuis, Jonathan Mizrahi, Christopher Monroe. [Active stabilization of ion trap radiofrequency potentials](https://aip.scitation.org/doi/10.1063/1.4948734). *Review of Scientific Instruments*, 2016.

### 2015

Kale G. Johnson, Brian Neyenhuis, Jonathan Mizrahi, J. David Wong-Campos, Christopher Monroe. [Sensing atomic motion from the zero point to room temperature with ultrafast atom interferometry](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.115.213001). *Physical Review Letters*, 2015.

### 2014

J. E. Hoffman, S. Ravets, J. A. Grover, P. Solano, P. R. Kordell, J. David Wong-Campos, L. A. Orozco, S. L. Rolston. [Ultrahigh transmission optical nanofibers](https://aip.scitation.org/doi/10.1063/1.4879799). *AIP Advances*, 2014.

### 2013

S. Ravets, J. E. Hoffman, P. R. Kordell, J. David Wong-Campos, S. L. Rolston, L. A. Orozco. [Intermodal energy transfer in a tapered optical fiber: optimizing transmission](https://opg.optica.org/josaa/abstract.cfm?uri=josaa-30-11-2361). *Journal of the Optical Society of America A*, 2013.

### 2012

Pedro A. Sanchez-Serrano, J. David Wong-Campos, Servando Lopez-Aguayo, Julio C. Gutiérrez-Vega. [Engineering of nondiffracting beams with genetic algorithms](https://opg.optica.org/ol/abstract.cfm?uri=ol-37-24-5040). *Optics Letters*, 2012.




